# Generated by Django 3.2.9 on 2022-07-13 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management',
            name='manager',
        ),
        migrations.AlterField(
            model_name='department',
            name='management',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='job.management', verbose_name='Управление'),
        ),
    ]
