# Generated by Django 3.2.9 on 2022-07-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('В процессе', 'Выполняется'), ('Не начат', 'Не_начата'), ('Завершен', 'Завершена')], default='Не начат', max_length=11, verbose_name='Статус'),
        ),
    ]
