# Generated by Django 3.2.9 on 2022-07-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Не начат', 'Не_начата'), ('Завершен', 'Завершена'), ('В процессе', 'Выполняется')], default='Не начат', max_length=11, verbose_name='Статус'),
        ),
    ]
