# Generated by Django 3.2.9 on 2022-06-12 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in_process', 'Выполняется'), ('started', 'Начата'), ('not_started', 'Не_начата'), ('finished', 'Завершена')], default='not_started', max_length=11, verbose_name='Статус'),
        ),
    ]
