# Generated by Django 3.2.9 on 2022-06-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20220615_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('started', 'Начата'), ('in_process', 'Выполняется'), ('finished', 'Завершена'), ('not_started', 'Не_начата')], default='not_started', max_length=11, verbose_name='Статус'),
        ),
    ]
