# Generated by Django 3.2.9 on 2022-06-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20220612_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in_process', 'Выполняется'), ('not_started', 'Не_начата'), ('finished', 'Завершена'), ('started', 'Начата')], default='not_started', max_length=11, verbose_name='Статус'),
        ),
    ]
