# Generated by Django 3.2.9 on 2022-06-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('started', 'Начата'), ('finished', 'Завершена'), ('not_started', 'Не_начата'), ('in_process', 'Выполняется')], default='not_started', max_length=11, verbose_name='Статус'),
        ),
    ]
