# Generated by Django 3.2.9 on 2022-06-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in_process', 'Выполняется'), ('finished', 'Завершена'), ('started', 'Начата'), ('not_started', 'Не_начата')], default='not_started', max_length=11, verbose_name='Статус'),
        ),
    ]
