# Generated by Django 3.2.9 on 2022-07-13 12:04

import backend.apps.accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', backend.apps.accounts.managers.UserManager()),
            ],
        ),
    ]
