# Generated by Django 3.2.9 on 2022-06-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Директор', 'Директор'), ('Менеджер', 'Менеджер'), ('Специалист', 'Специалист')], default='Специалист', max_length=50, verbose_name='Роль'),
        ),
    ]
